// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6C9fpMli3e-dBJgsb4ySFGp874ITq_3E',
    appId: '1:1033185961184:web:9dab655b77b494f69cdc85',
    messagingSenderId: '1033185961184',
    projectId: 'da-appbansach',
    authDomain: 'da-appbansach.firebaseapp.com',
    databaseURL: 'https://da-appbansach-default-rtdb.firebaseio.com',
    storageBucket: 'da-appbansach.firebasestorage.app',
    measurementId: 'G-NSPZG7C5KX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCduzKhp2SOTnjmLOm7n2f51kD6rnMeudw',
    appId: '1:1033185961184:android:49eec1c40fc89d5d9cdc85',
    messagingSenderId: '1033185961184',
    projectId: 'da-appbansach',
    databaseURL: 'https://da-appbansach-default-rtdb.firebaseio.com',
    storageBucket: 'da-appbansach.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_l394VCZhmjOzA6KuWmw1cpw6nb59kvs',
    appId: '1:1033185961184:ios:3e8707d23c5912499cdc85',
    messagingSenderId: '1033185961184',
    projectId: 'da-appbansach',
    databaseURL: 'https://da-appbansach-default-rtdb.firebaseio.com',
    storageBucket: 'da-appbansach.firebasestorage.app',
    iosBundleId: 'com.example.appbansach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_l394VCZhmjOzA6KuWmw1cpw6nb59kvs',
    appId: '1:1033185961184:ios:3e8707d23c5912499cdc85',
    messagingSenderId: '1033185961184',
    projectId: 'da-appbansach',
    databaseURL: 'https://da-appbansach-default-rtdb.firebaseio.com',
    storageBucket: 'da-appbansach.firebasestorage.app',
    iosBundleId: 'com.example.appbansach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6C9fpMli3e-dBJgsb4ySFGp874ITq_3E',
    appId: '1:1033185961184:web:c76cf9d1d46eef6a9cdc85',
    messagingSenderId: '1033185961184',
    projectId: 'da-appbansach',
    authDomain: 'da-appbansach.firebaseapp.com',
    databaseURL: 'https://da-appbansach-default-rtdb.firebaseio.com',
    storageBucket: 'da-appbansach.firebasestorage.app',
    measurementId: 'G-02QK7WWTKH',
  );

}